name: Scala CI with couchbase
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java: [ '8' ]
        scala: [ '2.11.12', '2.12.14' ]
        couchbase: [ '4.6.5', '5.0.1' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up java ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - run: |
          docker run -d \
            --ulimit nofile=40960:40960 \
            --ulimit core=100000000:100000000 \
            --ulimit memlock=100000000:100000000 \
            --name cb \
            --net=host \
            -v `pwd`/cb-test-prepare.sh:/cb-test-prepare.sh \
            couchbase:enterprise-${{ matrix.couchbase }}

          for i in {1..5}; do
            docker exec cb /cb-test-prepare.sh && break || sleep 8;
          done

        working-directory: .
        shell: bash
      - name: Run tests
        run: sbt ++${{ matrix.scala }} test
